version: 0.1

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      # copy the contents of /build to S3
      - aws s3 cp --recursive --acl public-read ./build s3://aws-codebuild-test-s3
      # - aws s3 rm s3://aws-codebuild-test-s3 --recursive
      # - echo S3 bucket is cleared.
      # - aws s3 cp build/aws-codebuild-test-s3 s3://aws-codebuild-test-s3 --recursive
      # - echo Build completed on `date`

      # set the cache-control headers for service-worker.js to prevent
      # browser caching
      # - >
      #   aws s3 cp --acl public-read
      #   --cache-control="max-age=0, no-cache, no-store, must-revalidate"
      #   ./build/service-worker.js s3://aws-codebuild-test-s3/

      # set the cache-control headers for index.html to prevent
      # browser caching
      - >
        aws s3 cp --acl public-read 
        --cache-control="max-age=0, no-cache, no-store, must-revalidate" 
        ./build/index.html s3://aws-codebuild-test-s3/
artifacts:
  files:
    - "**/*"
  base-directory: build
